name: firebase_auth_impl
description: "Firebase-backed implementation of core_contracts AuthRepository."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local contract package
  core_contracts:
    path: ../core_contracts

  # Firebase (aligned with app_core)
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
