name: app_core
description: "Core features application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Firebase (aligned across repo)
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.10
  google_sign_in: ^6.3.0

  # Local packages
  core_contracts:
    path: ../packages/core_contracts
  firebase_auth_impl:
    path: ../packages/firebase_auth_impl

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/hummerred.png

# Launcher icon generation (Android). Enable ios:true later if/when needed.
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/hummerred.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/hummerred.png"
